<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <RootNamespace>MOD.Pms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MOD.Pms.Application.Contracts\MOD.Pms.Application.Contracts.csproj" />
    <ProjectReference Include="..\MOD.Pms.EntityFrameworkCore\MOD.Pms.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stimulsoft.Reports.Angular.NetCore" Version="2024.1.2" />
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="24.1.44" />
    <PackageReference Include="Syncfusion.EJ2.PdfViewer.AspNet.Core.Windows" Version="24.1.44" />
    <PackageReference Include="Syncfusion.EJ2.WordEditor.AspNet.Core" Version="24.1.44" />
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.AuditLogging.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.Identity.Pro.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.Account.Pro.Admin.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.OpenIddict.Pro.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.LanguageManagement.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Saas.Host.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.TextTemplateManagement.HttpApi" Version="8.0.1" />
    <PackageReference Include="Volo.Abp.Gdpr.HttpApi" Version="8.0.1" />
  </ItemGroup>

</Project>
